version: "3"

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.3
    ports:
    - 9200:9200
    environment:
      - node.roles=master,data
      - xpack.security.enabled=false
      - xpack.monitoring.collection.enabled=false
      #- xpack.monitoring.enabled=false
      - xpack.ml.enabled=false
      - ingest.geoip.downloader.enabled=false
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - http.cors.enabled=true
      - http.cors.allow-origin="*"
      - ES_JAVA_OPTS=-Xms512m -Xmx512m -Dmapper.allow_dots_in_name=true
